# Generated by Django 4.2.2 on 2023-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('question1', models.CharField(max_length=255)),
                ('answer1', models.CharField(max_length=255)),
                ('question2', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student')),
            ],
        ),
    ]
