# Generated by Django 4.2.2 on 2023-06-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DirectLinkApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
