# Generated by Django 4.2.2 on 2023-06-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230613_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='NaN', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
        migrations.AddField(
            model_name='student',
            name='security_answer_1',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='security_answer_2',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='security_question_1',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='security_question_2',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='NaN@NaN.NaN', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='NaN', max_length=50),
        ),
    ]
